name: Test code and app
on:
  push:
    paths:
      - b3_api/**
      - tests/**
      - .github/workflows/run_test.yaml
  pull_request:
    paths:
      - b3_api/**
      - tests/**
      - .github/workflows/run_test.yaml
jobs:
  test_api:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        id: checkout
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Install packages
        run: poetry install

      - name: Run tests
        run: poetry run pytest 
